name: flutter_application_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
 # assets:

  fonts:
  - family: Audiowide
    fonts:
      - asset: assets/fonts/Audiowide-Regular.ttf
  - family: Arial
    fonts:
      - asset: assets/fonts/ArialCE.ttf
      - asset: assets/fonts/arialceb.ttf
      - asset: assets/fonts/ArialCEBoldItalic.ttf
      - asset: assets/fonts/ArialCEItalic.ttf
      - asset: assets/fonts/ArialCEMTBlack.ttf
  
  assets:
      - assets/images/broadcastImages/Highschool_dxd_logo.png
      - assets/images/broadcastImages/Highschool_dxd_born_logo.png
      - assets/images/broadcastImages/Highschool_dxd_new_logo.png
      - assets/images/broadcastImages/Highschool_dxd_hero_logo.png
      - assets/images/broadcastImages/SoloLeveling_logo.jpg
      - assets/images/broadcastImages/UQHolder_logo.png
      - assets/images/broadcastImages/TheEminenceInShadow_logo.png
      - assets/images/broadcastImages/AkameGaKill_logo.png
      - assets/images/broadcastImages/KonoSuba_logo.png
      - assets/images/broadcastImages/Call_of_the_Night_logo.png
      - assets/images/broadcastImages/Shinchou_Yuusha_logo.png