import 'dart:io';

void main() {
  int position;
  Map<int, String> pokeliste = {
    1: 'Bisasam',
    2: 'Bisaknosp',
    3: 'Bisaflor',
    4: 'Glumanda',
    5: 'Glutexo',
    6: 'Glurak',
    7: 'Schiggy',
    8: 'Schillok',
    9: 'Turtok',
    10: 'Raupy',
    11: 'Safcon',
    12: 'Smettbo',
    13: 'Hornliu',
    14: 'Kokuna',
    15: 'Bibor',
    16: 'Taubsi',
    17: 'Tauboga',
    18: 'Tauboss',
    19: 'Rattfratz',
    20: 'Rattikal',
    21: 'Habitak',
    22: 'Ibitak',
    23: 'Rettan',
    24: 'Arbok',
    25: 'Pikachu',
    26: 'Raichu',
    27: 'Sandan',
    28: 'Sandamer',
    29: 'Nidoran (w)',
    30: 'Nidorina',
    31: 'Nidoqueen',
    32: 'Nidoran (m)',
    33: 'Nidorino',
    34: 'Nidoking',
    35: 'Piepi',
    36: 'Pixi',
    37: 'Vulpix',
    38: 'Vulnona',
    39: 'Pummeluff',
    40: 'Knuddeluff',
    41: 'Zubat',
    42: 'Golbat',
    43: 'Myrapla',
    44: 'Duflor',
    45: 'Giflor',
    46: 'Paras',
    47: 'Parasek',
    48: 'Bluzuk',
    49: 'Omot',
    50: 'Digda',
    51: 'Digdri',
    52: 'Mauzuí',
  };
}
